# Generated by Django 2.2.7 on 2020-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooksknow', '0002_auto_20200119_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(related_name='cuisines', to='cooksknow.Cuisine'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='settings',
            field=models.ManyToManyField(related_name='settings', to='cooksknow.Setting'),
        ),
    ]
