# Generated by Django 2.2.7 on 2020-01-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooksknow', '0003_auto_20200119_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='ReviewCuisines', to='cooksknow.Cuisine'),
        ),
        migrations.AddField(
            model_name='review',
            name='settings',
            field=models.ManyToManyField(blank=True, related_name='ReviewSettings', to='cooksknow.Setting'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='cuisines', to='cooksknow.Cuisine'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='settings',
            field=models.ManyToManyField(blank=True, related_name='settings', to='cooksknow.Setting'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
