# Generated by Django 2.2.7 on 2020-01-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooksknow', '0006_review_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hours',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Decent'), (3, 'Good'), (4, 'Great'), (5, 'Exceptional')], null=True),
        ),
    ]
