# Generated by Django 2.2.7 on 2020-01-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooksknow', '0007_auto_20200120_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='hours',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
