# Generated by Django 2.2.7 on 2020-01-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooksknow', '0008_auto_20200120_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
