# Generated by Django 2.2.7 on 2020-01-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooksknow', '0009_restaurant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cuisines',
        ),
        migrations.RemoveField(
            model_name='review',
            name='settings',
        ),
    ]
