# Generated by Django 2.2.7 on 2020-01-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooksknow', '0010_auto_20200122_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='options',
            field=models.TextField(max_length=20),
        ),
    ]
