# Generated by Django 2.2.7 on 2020-01-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='side',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(1, 'FOH'), (2, 'BOH'), (3, 'CHEF'), (4, 'GM')], max_length=4, null=True),
        ),
    ]
